# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM node:latest as build

# Set the working directory
WORKDIR /app

# Copy package.json / package-lock.json
COPY package*.json ./

# Install all the dependencies
RUN npm install

# Add the source code to app
COPY . .

# Install Nx CLI
RUN npm i -g nx

# Reset cached libs
RUN nx reset

# Generate the build of the application
RUN nx build amadeus-fi


# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the custom nginx configuration
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy the build output to replace the default nginx contents.
COPY --from=build /app/dist/apps/amadeus-fi /usr/share/nginx/html

# Expose port 80
EXPOSE 80
